# Generated by Django 5.2.8 on 2025-11-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('profesion', models.CharField(max_length=80)),
                ('correoElectronico', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
    ]
